arquivo2 = open ("C:/Users/Vinicius_wilbert/Documents/TXT/GOT.txt",'w')
arquivo2.write('Escrevendo no arquivo\n')
arquivo2.write('John Snow\n')
arquivo2.write('Arya Stark\n')
arquivo2.write('Sansa Stark\n')
arquivo2.write('Bran Stark\n')
arquivo2.close()
print('fim programa')